app/urls.py
from django.urls import path
from app.views import *
app_name = 'something'

urlpatterns = [
    path('first/',first,name ='first'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name = 'something2'

urlpatterns = [
    path('second/',second,name='second'),
]

project18/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request, 'mdb4.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def second(request):
    return render(request, 'html2.html')

templates/html2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page2</title>
    <link rel="stylesheet" href="{% static 'css/bootsrtap.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.css' %}">
</head>
<body>
        <!-- Card deck -->
    <div class="card-deck" >

        <!-- Card -->
        <div class="card mb-4" style="width: 25rem;">
    
        <!--Card image-->
        <div class="view overlay">
            <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.webp" style="width: 25rem;"
            alt="Card image cap">
            <a href="#!">
            <div class="mask rgba-white-slight"></div>
            </a>
        </div>
    
        <!--Card content-->
        <div class="card-body">
    
            <!--Title-->
            <h4 class="card-title">Card title</h4>
            <!--Text-->
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
            <button type="button" class="btn btn-light-blue btn-md">Read more</button>
    
        </div>
    
        </div>
        <!-- Card -->
    
        <!-- Card -->
        <div class="card mb-4" style="width: 25rem;">
    
        <!--Card image-->
        <div class="view overlay">
            <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/14.webp" style="width: 25rem;"
            alt="Card image cap">
            <a href="#!">
            <div class="mask rgba-white-slight"></div>
            </a>
        </div>
    
        <!--Card content-->
        <div class="card-body">
    
            <!--Title-->
            <h4 class="card-title">Card title</h4>
            <!--Text-->
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
            <button type="button" class="btn btn-light-blue btn-md">Read more</button>
    
        </div>
    
        </div>
        <!-- Card -->
    
        <!-- Card -->
        <div class="card mb-4" style="width: 25rem;">
    
        <!--Card image-->
        <div class="view overlay">
            <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/15.webp" style="width: 25rem;"
            alt="Card image cap">
            <a href="#!">
            <div class="mask rgba-white-slight"></div>
            </a>
        </div>
    
        <!--Card content-->
        <div class="card-body">
    
            <!--Title-->
            <h4 class="card-title">Card title</h4>
            <!--Text-->
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
            <button type="button" class="btn btn-light-blue btn-md">Read more</button>
    
        </div>
    
        </div>
        <!-- Card -->
    
    </div>
    <!-- Card deck -->
    <a href="{% url 'something:first' %}">Click here to navigate home page</a>







    <script src="{% static 'js/bootstarp.js' %}"></script>
    <script src="{% static 'js/mdb.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
</body>
</html>

templates/mdb4.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MDB4 Connection</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.css' %}">
</head>
<body>
    <center>
        <h1>MDB4 Connection</h1>
        <!-- Card -->
        <div class="card" style="width: 18rem;">

            <!-- Card image -->
            <div class="view overlay">
            <img class="card-img-top" src="{% static 'images/iron-man.png' %}" style="width: 18rem;"
                alt="Card image cap">
            <a href="#!">
                <div class="mask rgba-white-slight"></div>
            </a>
            </div>
        
            <!-- Card content -->
            <div class="card-body">
        
            <!-- Title -->
            <h4 class="card-title">Iron-man</h4>
            <!-- Text -->
            <p class="card-text">The legend, the Avenger, the protector of the world , The Iron-man, Man with huge legacy</p>
            <!-- Button -->
            <a href="https://en.wikipedia.org/wiki/Iron_Man_(2008_film)" class="btn btn-primary">click here to know more</a>
        
            </div>
        
        </div>
        <!-- Card -->
        <br>
        <!-- Card Narrower -->
        <div class="card card-cascade narrower" style="width: 18rem;">

            <!-- Card image -->
            <div class="view view-cascade overlay">
            <img class="card-img-top" src="{% static 'images/goku.png' %}" style="width: 18rem;"
                alt="Card image cap">
            <a>
                <div class="mask rgba-white-slight"></div>
            </a>
            </div>
        
            <!-- Card content -->
            <div class="card-body card-body-cascade">
        
            <!-- Label -->
            <h5 class="pink-text pb-2 pt-1"><i class="fas fa-utensils"></i> goku</h5>
            <!-- Title -->
            <h4 class="font-weight-bold card-title">Goku</h4>
            <!-- Text -->
            <p class="card-text">One of the legend from Manga series the beast Goku</p>
            <!-- Button -->
            <a class="btn btn-unique">More about me</a>
        
            </div>
        
            <!-- Card footer -->
            <div class="card-footer text-muted text-center">
            4 days ago
            </div>
        
        </div>
        <!-- Card Narrower -->
        <a href="{% url 'something2:second' %}">Click here to go to the next Page2</a>

    </center>
    








    <script src="{% static 'js/bootstarp.js' %}"></script>
    <script src="{% static 'js/mdb.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
</body>
</html>